# permissions for end users to view clusterwidenetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  name: clusterwidenetworkpolicy-viewer-role
rules:
- apiGroups:
  - networking.linode.com
  resources:
  - clusterwidenetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.linode.com
  resources:
  - clusterwidenetworkpolicies/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
