---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linode-firewall-manager-role
rules:
- apiGroups:
  - networking.linode.com
  resources:
  - clusterwidenetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.linode.com
  resources:
  - clusterwidenetworkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - networking.linode.com
  resources:
  - clusterwidenetworkpolicies/status
  verbs:
  - get
  - patch
  - update
